
create table tbl1 (
  id integer generated by default as identity primary key,
  name varchar
);

create table tbl2 (
  id integer generated by default as identity primary key,
  name varchar,
  count integer
);

create table tbl3 (
  id integer generated by default as identity primary key,
  name varchar,
  kind varchar
);

insert into tbl3 (name, kind) values ('Meta table', 'META');

create table tbl4 (
  id integer generated by default as identity primary key,
  name varchar,
  kind varchar,
  live bool
);

create table tbl5 (
  id integer generated by default as identity primary key,
  name varchar,
  kind varchar,
  deleted bool
);

