#!/usr/bin/env ruby

require_relative '../lib/prick/lang.rb'

require 'shellopts'

SPEC = %(
  @ Compile a prick file

  -- CMD [UID] [VAR=VAL...]


  BUILD

  MAKE

  RUN


  -f,file=FILE|DIR
    Prick source file. The default is the 'make.prick' file in the project main
    directory

  -X,exception
    Throw exceptions instead of using ShellOpts error message. Useful to
    pinpoint the source of an error when developing

  -D,dump=token|tokens|ast|idr|dep|state?
    Dump debug. Default is 'ast'

  -T,trace
    Enable tracer. Used for debugging

  Syntax

    PROGRAM ::= BLOCK

    BLOCK ::= STMT+

    STMT ::=
        DECL_STMT
      | PHASE-STMT
      | OPTION_STMT
      | PROVIDE-STAT
      | REQUIRE_STMT
      | MAKE-STMT
      | IF-STMT
      | CASE-STMT
      | COMMAND-STMT
      | FILE-STMT
      | DUMP-STMT
      | LOAD-STMT
      | SNAPSHOT-STMT
      | RESTORE-STMT
      | RETURN-STMT

    DECL-STMT ::=
        schema IDENT BLOCK-ARGS
      | function IDENT BLOCK-ARGS

    PHASE-STMT ::=
        [init | term | meta | seeds | auth] BLOCK-ARGS

    OPTION_STMT ::=
      # TODO

    PROVIDE-STMT ::=
      provide IDENT

    REQUIRE-STMT ::=
      require REF+

    MAKE-STMT ::=
      make FILE+ from PATH+
        BLOCK
      end

    IF-STMT ::=
        if EXPR BLOCK end
      | if EXPR BLOCK else BLOCK end
      | if EXPR BLOCK ( elsif EXPR <NL> BLOCK )+ ( else BLOCK )? end

    CASE-STMT ::=
        case VAR-EXPR WHEN-STMT... [ else COMMAND... ] end

    WHEN-STMT ::=
        when ( EXPR | OPER EXPR )+ COMMAND...

    COMMAND-STMT ::=
        exec SOURCE
      | eval SOURCE
      | ruby RUBY_SCRIPT ARGUMENTS...
      | sql SOURCE
      | call REF+

    DUMP-STMT ::=
      dump BACKUP BACKUP_KINDS OBJECT_BLOCK
      load BACKUP ( schema | data )? OBJECT_BLOCK
      snapshot BACKUP OBJECT_BLOCK
      restore BACKUP OBJECT_BLOCK

    FILE-STMT ::= FILE+

    EXIT-STMT ::= return INTEGER

    BLOCK-ARGS ::=
        COMMAND-STMT
      | FILE-STMT...
      | BLOCK

    EXPR ::=
        PREFIX_OP EXPR
      | EXPR BINARY_OP EXPR
      | EXPR SUFFIX_OP
      | VARIABLE
      | LITERAL

    VARIABLE ::=
        BUILTIN_VARIABLES
      | COMMAND_VARIABLES
      | ENVIRONMENT_VARIABLES

    BUILTIN_VARIABLES ::=
        '$prj'
      | '$env'
      | '$ver'
      | '$cmd'
      | '$user'

    COMMAND_VARIABLES ::=
        '$' DOWNCASED_IDENTIFIER

    ENVIRONMENT_VARIABLES ::=
        '$' UPCASED_IDENTIFIER

    PREFIX_OP ::=
        '!'

    INFIX_OP ::=
        '&&'
      | '||'
      | '<='
      | '<'
      | '=='
      | '='
      | '!='
      | '>='
      | '>'
      | '~>'

    SUFFIX_OP ::=
        '?'

    # Files
    PATH ::= <path> '/' <*>
    FILE ::= <path> '/' <*.sql> | <*.psql> | <*.fox> | <*.prick> | <*.rb>

    # Reference & identifier
    REF ::= .? IDENT ( . IDENT )*
    IDENT ::= /[\w.]+/

    # Inline source
    SOURCE ::=
        <line>
      | '|' <indented lines>

)

opts, args = ShellOpts.process(SPEC, ARGV)

file = opts.file || 'make.prick'
USE_EXCEPTION = opts.exception?
Trace.enable if opts.trace?
ShellOpts.exception = USE_EXCEPTION

# Extract command
cmd = args.extract(1)
%w(build make run).include?(cmd) or ShellOpts::error "Illegal command: #{cmd}"

# Extract uid
uid = args.first&.index('=').nil? && args.shift || '<main>'

# Extract variable assignments
VARIABLES = {}
if arg = args.shift
  case arg
    when /^(\w+)=(\S*)$/
      VARIABLES[$1.to_sym] = $2
    else
      ShellOpts::error "Illegal argument '#{arg}'"
  end
end

# Handle dump option
if opts.dump?
  kind = opts.dump || "ast"
  Prick::Lang::DUMP_KINDS.include?(kind) or
      ShellOpts::error "Illegal value for --dump '#{kind}'"
  Prick::Lang.dump(file, kind, uid, variables: VARIABLES)
  exit
end

# Compile
compiler = Prick::Lang::Compiler.new(file)
begin
  compiler.compile(variables: VARIABLES)
rescue => ex
  raise Prick::Lang::ErrorFunctions.pretty_backtrace!(ex)
end

__END__
    EXPR ::=
        CONSTANT-EXPR
      | RESOURCE-EXPR
      | ! EXPR
      | EXPR && EXPR
      | EXPR || EXPR
      | '(' EXPR ')'

    # 'env', 'cmd', and 'user' or's their arguments together, 'version' and's
    # them
    CONSTANT-EXPR ::=
        env IDENT+
      | cmd IDENT+
      | user IDENT+
      | version VER_EXPR+
      | var IDENT IDENT+

    RESOURCE-EXPR ::=
        schema IDENT
      | object REF
      | resource REF

    IDENT-EXPR ::=
      IDENT IDENT-OP
      IDENT ==|!= IDENT-OR-STRING

    VAR-EXPR ::= env | cmd | user | version | schema | object | resource

    VER-EXPR ::= VER-OP VER

    VAL-EXPR ::=
        IDENT
      | VER
      | VER-EXPR


