#!/usr/bin/env ruby

require_relative '../lib/prick/lang.rb'

require 'shellopts'

SPEC = %(
  @ Compile a prick file

  -- FILE

  -x,exception
    Throw exceptions instead of using ShellOpts error message. Useful to
    pinpoint the source of an error when developing

  Syntax

    SOURCE-FILE ::= STMT...

    STMT ::=
        DECL_STMT
      | options TODO
      | require SCHEMANAME|GROUPREF
      | IF-STMT
      | CASE-STMT
      | PHASE-STMT
      | GROUP-STMT
      | COMMAND-STMT
      | FILE-STMT
      | EXIT-STMT

    DECL-STMT ::=
        schema SCHEMA_NAME BLOCK-ARGS
      | gruop SCHEMA_NAME BLOCK-ARGS

    OPTION_STMT ::=
      # TODO

    REQUIRE_STMT ::=
      require SCHEMANAME|GROUPREF

    IF-STMT ::=
        if PRICK-EXPR|BLOCK then COMMAND... end
      | if PRICK-EXPR|BLOCK then COMMAND... else COMMAND... end
      | if PRICK-EXPR|BLOCK then COMMAND... elsif PRICK-EXPR... end

    EXPR ::=
        SIMPLE-EXPR
      | ! EXPR
      | EXPR && EXPR
      | EXPR || EXPR
      | '(' EXPR ')'

    SIMPLE-EXPR ::=
        env ENVIRONMENT+
      | cmd COMMAND+
      | version VERSION_OP VERSION
      | schema SCHEMANAME
      | object OBJECTREF
      | group GROUPREF

    VAR-EXPR ::= env | cmd | version | schema | object | group

    VAL-EXPR ::=
        IDENT
      | OBJECTREF
      | GROUPREF
      | VERSION

    CASE-STMT ::=
        case VAR-EXPR WHEN-STMT... [ else COMMAND... ] end

    WHEN-STMT ::=
        when PRICK-VALUE COMMAND...

    PHASE-STMT ::=
        [init | term | meta | seeds | auth] BLOCK-ARGS

    COMMAND-STMT ::=
        exec BASH-EXPR
      | eval BASH-EXPR
      | ruby RUBY_SCRIPT ARGUMENTS...
      | sql SQL-EXPR

    FILE-STMT ::= PATH...

    EXIT-STMT ::= exit INTEGER

    BLOCK-ARGS ::=
        COMMAND-STMT
      | FILE-STMT...
      |  BLOCK

    PRICK-EXPR ::=
        env PRICK-ENVIRONMENT...
      | cmd PRICK-COMMAND...
      | version VERSION...
      | user USER...

    PRICK-VALUE ::=
        PRICK-ENVIRONMENT...
      | PRICK-COMMAND...

    BASH-EXPR ::= '|' <indented lines>

    PATH ::= <path>/FILE
    FILE ::= <*.sql> | <*.psql> | <*.fox> | <*.prick> | <*.rb>


    PRICK-EXPR-KIND ::= 'env' | 'cmd' | <more-to-come>
    PRICK-ENVIRONMENT ::= 'proc' | 'dev' | 'test' | <user-defined>
    PRICK-COMMAND ::= 'build' | 'rebuild' | 'make' | 'run' | <detected-dynamically>

    SCHEMANAME ::= IDENT
    OBJECTNAME ::= IDENT
    OBJECTREF ::= SCHEMA_NAME.OBJECT_NAME
    GROUPNAME ::= IDENT
    GROUPREF ::= SCHEMA_NAME(::GROUP_NAME)+

    IDENT ::= /[\w.]+/
    REF ::=
)

opts, args = ShellOpts.process(SPEC, ARGV)

USE_EXCEPTION = opts.exception?

file = args.expect(1)

compiler = Prick::Lang::Compiler.new(file)

begin
  compiler.compile
rescue => ex
  raise Prick::Lang::ErrorFunctions.pretty_backtrace!(ex)
end

