
module Prick::Lang
  class Parser
    using String::Text
    include ErrorFunctions
#   class ParserError < Prick::Lang::Error; end # FIXME Not used

    CONSTANTS = [:ENV, :CMD, :USER, :VAR, :VERSION, :SCHEMA, :OBJECT, :RESOURCE]
    COMMANDS = [:EXEC, :EVAL, :RUBY, :SQL, :CALL]

    # Map from operator token kind to tuple of priority, associtivity (:left
    # or :right), and arity. Used by the shunter
    OPERATORS = {
      OROR: [0, :left, 2],
      ANDAND: [1, :left, 2],
      LT: [2, :left, 2],
      LE: [2, :left, 2],
      EQEQ: [2, :left, 2],
      NEQ: [2, :left, 2],
      GE: [2, :left, 2],
      GT: [2, :left, 2],
      EXCLAIM: [3, :right, 1]
    }.map { |k,v| [k, { prior: v[0], assoc: v[1], arity: v[2] } ] }.to_h

    # Operators for comparing versions
    VERSION_OPERATORS = Set[:LT, :LE, :EQEQ, :NEQ, :GE, :GT, :TIGT]

    def file = @tokenizer.file
    attr_reader :tokenizer

    # The AST generated by #parse
    attr_reader :ast

    def initialize(tokenizer)
      @tokenizer = tokenizer
      @ast = nil
    end

    def parse
      @ast = parse_program
      if !@tokenizer.peek? # Can't use #eof? because we may have to scan through comments
        unexpected_token_error "end of file"
      end
      @ast
    end

    def inspect = "<Parser: #{file}>"

  protected
    def parse_program
      trace
      @ast = Ast::Program.new(file)
      @ast.block = parse_block
      @ast
    end

    def parse_stmt
      trace
#     puts "  peek: #{peek.inspect}"
      case peek&.kind
        when :SCHEMA; parse_decl(Ast::Schema, read)
        when :FUNCTION; parse_decl(Ast::Function, read)
        when :OPTIONS; parse_options
        when :PROVIDE; parse_provide
        when :REQUIRE; parse_require
        when :IF; parse_if
        when :CASE; parse_case
        when :INIT, :TERM, :META, :SEEDS, :AUTH; parse_decl(Ast::Phase, peek)
        when :EXEC, :EVAL, :SQL; parse_command
        when :CALL; parse_call
        when :RUBY; not_implemented_error "'ruby' command"
        when :FILE; parse_source
      else
        return nil
      end
    end

    def parse_stmts(check: true)
      trace
      check_expected "statement" do
        stmts = []
        while stmt = parse_stmt
          stmts << stmt
        end
        check && stmts.empty? ? nil : stmts # nil triggers enclosing #check_expected
      end
    end

    # Parse a statement block (a list of statements). Checks for non-empty when
    # :check is true (the default)
    #
    def parse_block(token = nil, check: true)
      trace token, peek
      check_expected "block" do
        block = Ast::Block.new(token) # Note that token may be nil, it is assigned later if so
        block.stmts = parse_stmts
        next nil if block.stmts.empty? && check
        block.token ||= block.start_token # Default token to start token
        block
      end
    end


    # Schema, phase, or function declarations. Uses that they have the same
    # parts
    def parse_decl(klass, token)
      trace token
      decl = klass.new(token)
      decl.ident = parse_name
      token = readkind(:BRACE_BEGIN)
      decl.block = parse_block(token, check: false)
      decl.block.stop_token = readkind(:BRACE_END)
      decl
    end

    def parse_provide
      provide = Ast::Provide.new(read)
      provide.ident = parse_name
      provide
    end

    def parse_require
#     puts "#parse_require"
      require_ = Ast::Require.new(read)
      require_.references = parse_references
      require_
    end

    def parse_command
#     puts "#parse_command"
      command = Ast::ExternalCommand.new(read)
      if peek.kind == :PIPE
        min_indent = @tokenizer.indent + 1
        read
        command.source = readtext(min_indent)&.text
      else
        command.source = readline&.text
      end or unexpected_token_error peek, "command"
      command
    end

    def parse_source
      source = Ast::Source.new peek
      source.files = parse_files
      source
    end

    def parse_call
      call = Ast::CallCommand.new(read)
      call.references = parse_references
#     readkinds(:REF, :IDENT).each { call.references << Ast::Reference.new(_1) }
      call
    end

    def parse_if
      trace
      if_ = Ast::If.new(peek)
      loop do
        if_then = Ast::IfThen.new(read)
        if_then.expr = parse_expr
        if_then.then_ = parse_block
        if_.if_thens << if_then
        break if peek.kind != :ELSIF
      end
      if peek.kind == :ELSE
        read
        if_.else_ = parse_block
      end
      readkind(:END)
      if_
    end

    def parse_case
      case_ = Ast::Case.new(read)
      case_.const = parse_constant
      while peek.kind == :WHEN
        when_ = Ast::When.new(read)
        when_.values = parse_values
        when_.then_ = parse_block
        case_.whens << when_
      end
      !case_.whens.empty? or unexpected_token_error peek, "'when'"
      if peek.kind == :ELSE
        read
        case_.else_ = parse_block
      end
      readkind(:END)
      case_
    end

    # Parse an expression. It uses the shunter to compile the source into
    # reverse polish notation that is then converted into an Ast::Expr
    def parse_expr
      trace
      stack = []
      shunt_exprs.each { |token| # Token is either a SimpleExpr or a operator token
        if token.is_a? Ast::SimpleExpr
          stack.push token
        else
          case OPERATORS[token.kind][:arity]
            when 1
              e = Ast::UnExpr.new(token)
              e.expr = stack.pop
              stack.push e
            when 2
              e = Ast::BinExpr.new(token)
              e.rexpr = stack.pop
              e.lexpr = stack.pop
              stack.push e
          end
        end
      }
      stack.first or unexpected_token_error read, "expression"
    end

    # Parses list of words (cmd, env, user). Note: Called from the shunter to
    # generate simple expressions
    def parse_simple_expr # token should be equal to #peek
      trace
      token = read(eol: true)
      case token.kind
        when :CMD, :ENV, :USER
          expr = Ast::RuntimeExpr.new(token)
          expr.ident = Ast::Ident.new(expr.token)
          expr.words = parse_idents
        when :VAR
          expr = Ast::RuntimeExpr.new(token)
          expr.ident = Ast::Ident.new(readkind(:IDENT, :CMD, :ENV, :USER))
          expr.words = parse_idents
        when :SCHEMA
          expr = Ast::ReferenceExpr.new(token)
          expr.ref = Ast::Reference.new(readkind *Token::IDENTS)
        when :OBJECT
          expr = Ast::ReferenceExpr.new(token)
          expr.ref = Ast::Reference.new(readkind *Token::REFS)
        when :RESOURCE
          expr = Ast::ReferenceExpr.new(token)
          expr.ref = Ast::Reference.new(readkind *Token::REFS)
        when :VERSION
          expr = Ast::VersionExpr.new(token)
          while VERSION_OPERATORS.include?(peek(eol: true).kind)
            match = Ast::VersionMatch.new(read(eol: true))
            match.version =  Ast::Ver.new(readkind(:VER, eol: true))
            expr.matches << match
          end
          !expr.matches.empty? or unexpected_token_error peek, "version operator"
      else
        unexpected_token_error peek, "simple expression"
      end
      expr
    end

    def parse_values
      readwhile { parse_value? }
    end

    def parse_ruby
      not_implemented_error "#parse_ruby"
    end

    # Parse a list of files. Return array of File objects. Raise an error if
    # the array is empty and :check is true
    #
    def parse_files(check: true)
#     puts "#parse_files"
      check_expected "files" do
        r = []
        while !@tokenizer.eof? && (token = peek) && token.kind == :FILE
          r << Ast::File.new(read)
        end
        check && r.empty? ? nil : r # nil triggers enclosing #check_expected
      end
    end

    def parse_ident?
      trace
      return nil if @tokenizer.eol?
      token = peek(eol: true)
      Token::IDENTS.include?(token.kind) ? Ast::Ident.new(read(eol: true)) : nil
    end
    def parse_ident = Ast::Ident.new(readkind(*Token::IDENTS, eol: true))

    def parse_idents? = readwhile? { parse_ident? }
    def parse_idents
      trace
      check_expected("identifier", eol: true) { readwhile { parse_ident? } }
    end

    # Single-component reference used in declarations. It parsed as a Reference object
    # because we later want to compute the uid
    def parse_name = Token::IDENTS.include?(peek&.kind) ? Ast::Reference.new(read) : nil
    def parse_name? = Ast::Reference.new(readkind(Token::IDENTS))

    def parse_reference? = Token::REFS.include?(peek.kind) ? Ast::Reference.new(read) : nil
    def parse_reference = Ast::Reference.new(readkind(*Token::REFS))

    def parse_references? = readwhile? { parse_reference? }
    def parse_references = check_expected("reference") { readwhile { parse_reference? } }

    # Parse a space-separated list of values. Values are IDENT, REF, or a version match
    def parse_value?
      case peek.kind
        when *Token::REFS
          Ast::Reference.new(read)
        when :VER # Default '==' operator
          tk = read
          oper = Token.new(tk.file, tk.lineno, tk.charno, "==", :EQEQ)
          match = Ast::VersionMatch.new(oper)
          match.version = Ast::Ver.new(tk)
          match
        when *VERSION_OPERATORS
          match = Ast::VersionMatch.new(read)
          match.version = Ast::Ver.new(readkind(:VER))
          match
      else
        nil
      end
    end

    def parse_constant
      Ast::Const.new(readkind(*CONSTANTS))
    end
    #
    # T O K E N I Z E R  I N T E R F A C E
    #

    # Functions from tokenizer with error handling
    #
    def peek(**opts) = @tokenizer.peek(**opts) or error(@tokenizer.error_token)
    def peek?(**opts) = @tokenizer.peek(**opts)

    def read(**opts) = @tokenizer.read(**opts) or error(@tokenizer.error_token)
    def read?(**opts) = @tokenizer.read(**opts)

    def readline?(**opts) = @tokenizer.readline(**opts)
    def readline(**opts) = @tokenizer.readline(**opts) or error(@tokenizer.error_token)

    def readtext?(indent, **opts) = @tokenizer.readtext(indent, **opts)
    def readtext(indent, **opts) = @tokenizer.readtext(indent, **opts) or error(@tokenizer.error_token)

    def readkind?(*kinds, **opts) = kinds.include?(peek(**opts)&.kind) ? read(**opts) : nil
    def readkind(*kinds, **opts) = readkind?(*kinds, **opts) or unexpected_token_error kinds
    # Note: Returns an empty list if no token was found
    def readkinds?(*kinds, **opts)
      a = []
      while kinds.include? peek(**opts)&.kind
        a << read(**opts)
      end
      a
    end
    def readkinds(*kinds, **opts) = [readkind(*kinds, **opts)] + readkinds?(kinds, **opts)

    # Return nil if empty
    def readwhile(&block) = (r = readwhile?(&block)).empty? ? nil : r

    # Note: Returns an empty list if no token was found
    def readwhile?(&block)
      a = []
      r = yield
      while r
        a << r
        r = yield
      end
      a
    end

    #
    # S H U N T I N G
    #

    # if a ||
    #   b
    # if schema
    #   a

    # Returns a reversed Polish notation list of SimpleExpression objects and operator tokens
    def shunt_exprs
      trace
#     puts "#shunt_exprs"
      stack = []
      output = []
      token_args = {} # Map from list operators 'env' and 'cmd' to array of arguments

      accept_eol = true
      while token = tokenizer.peek(eol: true)
        case token.kind
          when :EOL
            break if !accept_eol
            read(eol: true)
          when :PAREN_BEGIN
            accept_eol = true
            stack.push(read(eol: true))
          when :PAREN_END
            accept_eol = true
            read(eol: true)
            while op = stack.pop and op.kind != :PAREN_BEGIN
              output << op
            end
          when *CONSTANTS
            accept_eol = false
            output << parse_simple_expr
          else
            accept_eol = false
            oper = OPERATORS[token.kind] or break
            read eol: true
            while top = OPERATORS[stack.last&.kind]
              break if oper[:prior] > top[:prior]
              break if oper[:prior] == top[:prior] && oper[:assoc] == :right
              output << stack.pop
            end
            stack.push token
        end
      end

      output + stack.reverse
    end

    #
    # E R R O R   H A N D L I N G
    #

    # :call-seq:
    #   unexpected_token_error(token = @tokenizer.error_token || @tokenizer.token, *words)
    #
    # Raise an error with the message format
    #
    #   Expected WORD, ..., or WORD, got WORD
    #
    # The error will be located at the given token (default @tokenizer #error or
    # #token). Note that it does not check for an error, it only displays it
    #
    # Some prettyfication is done on words
    #
    def unexpected_token_error(*args)
      token = args.first.is_a?(Token) ? args.shift : @tokenizer.error || @tokenizer.peek_error || @tokenizer.token or
          raise ArgumentError
      words = Array(*args).flatten.map! { |w| w.is_a?(Symbol) ? Token::TEXTS[w] : w }
      words = seq words
      source = token.respond_to?(:error) && token.error || token.text
      got = (source.empty? ? "" : ", got '#{source}'")
      message = "Expected #{words}#{got}"
      error token, message
    end

    def check_expected(words, eol: false, &block)
      trace words, eol: eol
#     token = peek(eol: eol)
#     if token.kind == :EOL
#       error token, words
#     else

#     token = peek(eol: eol)

      token = peek(eol: eol) and token.kind != :EOL and r = yield(token) or unexpected_token_error token, words
      r
    end

    def not_implemented_error(*args)
      token = args.first.is_a?(Token) ? args.shift : @tokenizer.error || @tokenizer.peek_error || @tokenizer.token
      token or raise ArgumentError
      method_name = args.shift
      message = "#{method_name} is not implemented"
      error token, message
    end

    #
    # U T I L I T I E S
    #

    # English language sequence of words. Eg 'a, b, or c'
    def seq(words)
      words.map!(&:to_s)
      case words.size
        when 1; words.first
        when 2; words.join(" or ")
        else words[0..-2].join(", ") + ", or " + words.last
      end
    end
  end
end


