
module Prick::Lang
  class Parser
    using String::Text
    include ErrorFunctions
#   class ParserError < Prick::Lang::Error; end # FIXME Not used

    CONSTANTS = [:ENV, :CMD, :USER, :VERSION, :SCHEMA, :OBJECT, :RESOURCE]
    COMMANDS = [:EXEC, :EVAL, :RUBY, :SQL, :CALL]

    # Map from operator token kind to tuple of priority, associtivity (:left
    # or :right), and arity. Used by the shunter
    OPERATORS = {
      OROR: [0, :left, 2],
      ANDAND: [1, :left, 2],
      LT: [2, :left, 2],
      LE: [2, :left, 2],
      EQEQ: [2, :left, 2],
      NEQ: [2, :left, 2],
      GE: [2, :left, 2],
      GT: [2, :left, 2],
      EXCLAIM: [3, :right, 1]
    }.map { |k,v| [k, { prior: v[0], assoc: v[1], arity: v[2] } ] }.to_h

    # Operators for comparing versions
    VERSION_OPERATORS = Set[:LT, :LE, :EQEQ, :NEQ, :GE, :GT, :TIGT]

    def file = @tokenizer.file
    attr_reader :tokenizer

    # The AST generated by #parse
    attr_reader :ast

    def initialize(tokenizer)
      @tokenizer = tokenizer
      @ast = nil
    end

    def parse
      @ast = parse_program
      if !@tokenizer.eof?
        unexpected_token_error "end of file"
      end
      @ast.build_tree
      @ast
    end

    def inspect = "<Parser: #{file}>"

#   def dump
#     puts self.class
#     indent { puts "file: #{file}" }
#   end

  protected
    def parse_program
#     puts "#parse_program"
      @ast = Ast::Program.new(file)
      @ast.block = parse_block
      @ast
    end

    def parse_stmt
#     puts "#parse_stmt"
      case peek&.kind
        when :SCHEMA, :FUNCTION; parse_decl
        when :OPTIONS; parse_options
        when :PROVIDE; parse_provide
        when :REQUIRE; parse_require
        when :IF; parse_if
        when :CASE; parse_case
        when :INIT, :TERM, :META, :SEEDS, :AUTH; parse_phase
        when :EXEC, :EVAL, :SQL; parse_command
        when :CALL; parse_call
        when :RUBY; not_implemented_error "'ruby' command"
        when :FILE; parse_source
      else
        return nil
      end
    end

    def parse_stmts(check: true)
#     puts "#parse_stmts"
      check_expected "statement" do
        stmts = []
        while stmt = parse_stmt
          stmts << stmt
        end
        check && stmts.empty? ? nil : stmts # nil triggers enclosing #check_expected
      end
    end

    # Parse a statement block (a list of statements). Checks for non-empty when
    # :check is true (the default)
    #
    def parse_block(token = nil, check: true)
#     puts "#parse_block"
      check_expected "block" do
        block = Ast::Block.new(token) # Note that token may be nil, it is assigned later if so
#       indent {
#       puts "--------------"
#       p block.stmts
#       p block.stmts.class
#       puts "--------------"

#       p block.stmts.empty?
        stmts = parse_stmts
#       p stmts
        block.stmts = stmts
#       p block.stmts
#       block.stmts = parse_stmts
#       p block.stmts.empty?
#       p block.stmts
#       p :BING
        next nil if block.stmts.empty? && check
#       p :BANG
#       }
         block.token ||= block.start_token # Default token to start token
        block
      end
    end

    # Parse a block expression
    #
    #   { ... }
    #   FILE...
    #   COMMAND
    #
    def parse_block_argument
      check_expected %w(block command file) do |token|
        if token.kind == :BRACE_BEGIN
          block = parse_block(read, check: false)
          block.stop_token = readkind(:BRACE_END)
        else # Create a one-statement block
          block = Ast::Block.new(token)
          case token.kind
            when :FILE;
              source = Ast::Source.new(token)
              source.files.concat(parse_files)
              block.stmts << source
            when *COMMANDS; block.stmts << parse_command
          else
            nil
          end
        end
        block
      end
    end

    def parse_call
      call = Ast::CallCommand.new(read)
      readkinds(:REF, :IDENT).each { call.refs << Ast::Reference.new(_1) }
      call
    end

    # Schema or function declaration
    def parse_decl
#     puts "parse_decl"
      decl = Ast::Decl.new(read)
      decl.ident = parse_ident
      decl.block = parse_block_argument
      decl
    end

    def parse_provide
      provide = Ast::Provide.new(read)
      provide.ident = parse_ident
      provide
    end

    def parse_require
#     puts "#parse_require"
      require_ = Ast::Require.new(read)
      readkinds(:REF, :IDENT).each { require_.refs << Ast::Reference.new(_1) }
      require_
    end

    # init, data, meta, etc. phases
    def parse_phase
#     puts "parse_phase"
      phase = Ast::Phase.new(read)
      phase.block = parse_block_argument
      phase
    end

    def parse_command
#     puts "#parse_command"
      command = Ast::ExternalCommand.new(read)
      if peek.kind == :PIPE
        min_indent = @tokenizer.indent + 1
        read
        command.source = readtext(min_indent)&.text
      else
        command.source = readline&.text
      end or unexpected_token_error peek, "command"
      command
    end

    def parse_source
      source = Ast::Source.new peek
      source.files = parse_files
      source
    end

    def parse_if
#     puts "#parse_if"
      if_ = Ast::If.new(peek)
      loop do
        if_then = Ast::IfThen.new(read)
        if_then.expr = parse_expr
        if_then.then_ = parse_block
        if_.if_thens << if_then
        break if peek.kind != :ELSIF
      end
      if peek.kind == :ELSE
        read
        if_.else_ = parse_block
      end
      readkind(:END)
      if_
    end

    def parse_case
      case_ = Ast::Case.new(read)
      case_.const = parse_constant
      while peek.kind == :WHEN
        when_ = Ast::When.new(read)
        when_.values = parse_values
        when_.then_ = parse_block
        case_.whens << when_
      end
      !case_.whens.empty? or unexpected_token_error peek, "'when'"
      if peek.kind == :ELSE
        read
        case_.else_ = parse_block
      end
      readkind(:END)
      case_
    end

    # Parse an expression. It uses the shunter to compile the source into
    # reverse polish notation that is then converted into an Ast::Expr
    def parse_expr
#     puts "#parse_expr"
      stack = []
      shunt_exprs.each { |token| # Token is either a SimpleExpr or a operator token
        if token.is_a? Ast::SimpleExpr
          stack.push token
        else
          case OPERATORS[token.kind][:arity]
            when 1
              e = Ast::UnExpr.new(token)
              e.expr = stack.pop
              stack.push e
            when 2
              e = Ast::BinExpr.new(token)
              e.rexpr = stack.pop
              e.lexpr = stack.pop
              stack.push e
          end
        end
      }
      stack.first or unexpected_token_error read, "expression"
    end

    # Parses list of words (cmd, env, user). Note: Called from the shunter to
    # generate simple expressions
    def parse_simple_expr # token should be equal to #peek
#     puts "parse_simple_expr"
      case peek.kind
        when :CMD, :ENV, :USER
          expr = Ast::RuntimeExpr.new(read)
          expr.words = parse_idents
        when :SCHEMA
          expr = Ast::ReferenceExpr.new(read)
          expr.ref = Ast::Reference.new(readkind :IDENT)
        when :OBJECT
          expr = Ast::ReferenceExpr.new(read)
          expr.ref = Ast::Reference.new(readkind :REF, :IDENT)
        when :RESOURCE
          expr = Ast::ReferenceExpr.new(read)
          expr.ref = Ast::Reference.new(readkind :REF, :IDENT )
        when :VERSION
          expr = Ast::VersionExpr.new(read)
          while VERSION_OPERATORS.include?(peek.kind)
            match = Ast::VersionMatch.new(read)
            match.version = Ast::Ver.new(readkind(:VER))
            expr.matches << match
          end
          !expr.matches.empty? or unexpected_token_error peek, "version operator"
      else
        unexpected_token_error peek, "simple expression"
      end
      expr
    end

    def parse_values
      readwhile { parse_value? }
    end

    def parse_ruby
      not_implemented_error "#parse_ruby"
    end

    # Parse a list of files. Return array of File objects. Raise an error if
    # the array is empty and :check is true
    #
    def parse_files(check: true)
#     puts "#parse_files"
      check_expected "files" do
        r = []
        while !@tokenizer.eof? && (token = peek) && token.kind == :FILE
          r << Ast::File.new(read)
        end
        check && r.empty? ? nil : r # nil triggers enclosing #check_expected
      end
    end

    def parse_ident? = peek&.kind == :IDENT ? Ast::Ident.new(read) : nil
    def parse_ident = Ast::Ident.new(readkind(:IDENT))

    def parse_idents? = readwhile? { parse_ident? }
    def parse_idents = check_expected("identifier") { readwhile { parse_ident? } }

    def parse_refs
      readkinds(:IDENT, :REF).map { Ast::Reference.new _1 }
    end

    # Parse a space-separated list of values. Values are IDENT, REF, or a version match
    def parse_value?
      case peek.kind
        when :IDENT, :REF
          Ast::Reference.new(read)
        when :VER # Default '==' operator
          tk = read
          oper = Token.new(tk.file, tk.lineno, tk.charno, "==", :EQEQ)
          match = Ast::VersionMatch.new(oper)
          match.version = Ast::Ver.new(tk)
          match
        when *VERSION_OPERATORS
          match = Ast::VersionMatch.new(read)
          match.version = Ast::Ver.new(readkind(:VER))
          match
      else
        nil
      end
    end

    def parse_constant
      Ast::Const.new(readkind(*CONSTANTS))
    end

    #
    # S H U N T I N G
    #

    # Returns a reversed Polish notation list of SimpleExpression objects and operator tokens
    def shunt_exprs
#     puts "#shunt_exprs"
      stack = []
      output = []
      token_args = {} # Map from list operators 'env' and 'cmd' to array of arguments

      while token = peek
        case token.kind
          when :PAREN_BEGIN
            stack.push(read)
          when :PAREN_END
            read
            while op = stack.pop and op.kind != :PAREN_BEGIN
              output << op
            end
          when *CONSTANTS
            output << parse_simple_expr
          else
            oper = OPERATORS[token.kind] or break
            read
            while top = OPERATORS[stack.last&.kind]
              break if oper[:prior] > top[:prior]
              break if oper[:prior] == top[:prior] && oper[:assoc] == :right
              output << stack.pop
            end
            stack.push token
        end
      end

      output + stack.reverse
    end

    #
    # T O K E N I Z E R  I N T E R F A C E
    #

    # Functions from tokenizer with error handling
    # TODO: Check if **opts is actually used
    def peek(**opts) = @tokenizer.peek(**opts) or error(@tokenizer.error_token)
    def read(**opts) = @tokenizer.read(**opts) or error(@tokenizer.error_token)
    def readline(**opts) = @tokenizer.readline(**opts) or error(@tokenizer.error_token)
    def readtext(indent, **opts) = @tokenizer.readtext(indent, **opts) or error(@tokenizer.error_token)
    def readkind(*kinds, **opts) = readkind?(*kinds, **opts) or unexpected_token_error kinds
    def readkinds(*kinds, **opts) = [readkind(*kinds)] + readkinds?(kinds, **opts)

    # Return nil if empty
    def readwhile(&block) = (r = readwhile?(&block)).empty? ? nil : r

    # Functions from tokenizer that accepts a nil return. FIXME this sacrifices
    # run-time performance for code clarity
    def peek?(**opts) = @tokenizer.peek(**opts)
    def read?(**opts) = @tokenizer.read(**opts)
    def readline?(**opts) = @tokenizer.readline(**opts)
    def readtext?(indent, **opts) = @tokenizer.readtext(indent, **opts)

    def readkind?(*kinds, **opts)
      kinds.include? peek&.kind or return nil
      read
    end

    # Note: Returns an empty list if no token was found
    def readkinds?(*kinds, **opts)
      kinds = Array(kinds).flatten
      a = []
      while kinds.include? peek(**opts)&.kind
        a << read(**opts)
      end
      a
    end

    # Note: Returns an empty list if no token was found
    def readwhile?(&block)
      a = []
      r = yield
      while r
        a << r
        r = yield
      end
      a
    end

    #
    # E R R O R   H A N D L I N G
    #

    # :call-seq:
    #   unexpected_token_error(token = @tokenizer.error_token || @tokenizer.token, *words)
    #
    # Raise an error with the message format
    #
    #   Expected WORD, ..., or WORD, got WORD
    #
    # The error will be located at the given token (default @tokenizer #error or
    # #token). Note that it does not check for an error, it only displays it
    #
    # Some prettyfication is done on words
    #
    def unexpected_token_error(*args)
      token = args.first.is_a?(Token) ? args.shift : @tokenizer.error || @tokenizer.peek_error || @tokenizer.token or
          raise ArgumentError
      words = Array(*args).flatten.map! { |w| w.is_a?(Symbol) ? Token::TEXTS[w] : w }
      words = seq words
      source = token.respond_to?(:error) && token.error || token.text
      got = (source.empty? ? "" : ", got '#{source}'")
      message = "Expected #{words}#{got}"
      error token, message
    end

    def check_expected(words, &block)
      token = peek and r = yield(token) or unexpected_token_error token, words
      r
    end

    def not_implemented_error(*args)
      token = args.first.is_a?(Token) ? args.shift : @tokenizer.error || @tokenizer.peek_error || @tokenizer.token
      token or raise ArgumentError
      method_name = args.shift
      message = "#{method_name} is not implemented"
      error token, message
    end

    #
    # U T I L I T I E S
    #

    # English language sequence of words. Eg 'a, b, or c'
    def seq(words)
      words.map!(&:to_s)
      case words.size
        when 1; words.first
        when 2; words.join(" or ")
        else words[0..-2].join(", ") + ", or " + words.last
      end
    end
  end
end


