
module Prick::Lang
  # Extend Token with a group function
  class Token
    def group?(group) = Parser::GRAMMAR_GROUPS[group].include?(kind)
    def groups?(groups) = Parser::GRAMMAR_GROUPS.values_at(*groups).any? { _1.include?(kind) }
  end

  class Parser
    using String::Text
    include ErrorFunctions
    class ParserError < Prick::Lang::Error; end

    GRAMMAR_GROUPS = begin
      groups = {
        decl: [:SCHEMA, :GROUP],
        phase: [:INIT, :TERM, :META, :SEEDS, :AUTH],
        command: [:EXEC, :EVAL, :RUBY, :SQL],
        require: [:REQUIRE],
        file: [:FILE],
        punct: [:BEGIN_BLOCK, :END_BLOCK, :MULTILINE]
      }
      # FIXME what?
      groups.merge!({
        unit: groups[:command] + groups[:require] + groups[:file]
      })
    end

    CONSTANTS = [:ENV, :CMD, :USER, :VERSION, :SCHEMA, :OBJECT, :GROUP]

    # Map from operator token kind to tuple of priority, associtivity (:left
    # or :right), and arity. Used by the shunter
    OPERATORS = {
      OROR: [0, :left, 2],
      ANDAND: [1, :left, 2],
      LT: [2, :left, 2],
      LE: [2, :left, 2],
      EQEQ: [2, :left, 2],
      NEQ: [2, :left, 2],
      GE: [2, :left, 2],
      GT: [2, :left, 2],
      EXCLAIM: [3, :right, 1]
    }.map { |k,v| [k, { prior: v[0], assoc: v[1], arity: v[2] } ] }.to_h

    # Operators for comparing versions
    VERSION_OPERATORS = Set[:LT, :LE, :EQEQ, :NEQ, :GE, :GT, :TIGT]

    attr_reader :tokenizer
    forward_to :tokenizer, :compiler
    forward_to :compiler, :file

    # The AST generated by #parse
    attr_reader :ast

    def initialize(tokenizer)
      @tokenizer = tokenizer
      @ast = nil
    end

    def parse = parse_program

    def inspect = "<Parser: #{file}>"

    def dump
      puts self.class
      indent { puts "file: #{file}" }
    end

  protected
    def parse_program
#     puts "#parse_program"
      @ast = Ast::Program.new(file)
      parse_block(@ast)
      @ast
    end

    def parse_stmt(parent)
#     puts "#parse_stmt"
      case peek.kind
        when :SCHEMA, :GROUP; parse_decl parent
        when :OPTIONS; parse_options parent
        when :REQUIRE; parse_require parent
        when :IF; parse_if parent
        when :CASE; parse_case parent
        when :INIT, :TERM, :META, :SEEDS, :AUTH; parse_phase parent
        when :EXEC, :EVAL; parse_command parent
        when :RUBY; parse_ruby parent
        when :SQL; parse_sql parent
        when :FILE; parse_files parent
      else
        return nil
      end
    end

    # Parse a statement block (a list of statements). Checks for non-empty when
    # :check is true (the default)
    #
    def parse_block(parent, token = nil, check: true)
      check_expected "block" do
        block = Ast::Block.new(parent, token) # Note that token may be nil
        true until parse_stmt(block).nil?
        next nil if block.empty? && check
        block.token ||= block.start_token # Default token to start token
        block
      end
    end

    # Parse a block expression
    #
    #   { ... }
    #   FILE...
    #   COMMAND
    #
    def parse_block_argument(parent)
      check_expected %w(block command file) do |token|
        if token.kind == :BRACE_BEGIN
          block = parse_block(parent, read, check: false)
          block.stop_token = expect(:BRACE_END) or unexpected_token_error "}"
        else
          block = Ast::Block.new(parent, token)
          if token.kind == :FILE
            parse_files block
          elsif token.group? :command
            parse_command block
          else
            nil
          end
        end
        block
      end
    end

    # Schema or group declaration
    def parse_decl(parent)
#     puts "parse_decl"
      decl = Ast::Decl.new(parent, read)
      decl.ident = parse_ident(decl)
      decl.block = parse_block_argument(decl)
      decl
    end

    def parse_require(parent)
      require_ = Ast::Require.new(parent, read)
      readkinds(:OBJREF, :GRPREF, :IDENT).map { Ast::Reference.new(require_, _1) }
      require_
    end

    # init, data, meta, etc. phases
    def parse_phase(parent)
#     puts "parse_phase"
      phase = Ast::Phase.new(parent, read)
      phase.block = parse_block_argument(phase)
      phase
    end

    def parse_command(parent)
#     puts "#parse_command"
      command = Ast::Command.new(parent, token = read)
      if peek.kind == :PIPE
        min_indent = tokenizer.indent + 1
        read
        command.source = readtext(min_indent)&.text
      else
        command.source = readline&.text
      end or unexpected_token_error peek, "command"
      command
    end

    def parse_if(parent)
#     puts "#parse_if"
      if_ = Ast::If.new(parent, token = read)
      if_.if_thens = []
      loop do
        if_then = Ast::IfThen.new(if_, token)
        if_.if_thens << if_then
        if_then.expr = parse_expr(if_then)
        if_then.then_ = parse_block(if_then)
        break if peek.kind != :ELSIF
        read
      end
      if peek.kind == :ELSE
        read
        if_.else_ = parse_block(if_)
      end
      expect(:END)
      if_
    end

    def parse_case(parent)
      case_ = Ast::Case.new(parent, read)
      case_.const = parse_constant(case_)
      case_.whens = []
      while peek.kind == :WHEN
        when_ = Ast::When.new(case_, read)
        case_.whens << when_
        when_.values = parse_values(when_)
        when_.then_ = parse_block(when_)
      end
      !case_.whens.empty? or unexpected_token_eror peek, "'when'"
      if peek.kind == :ELSE
        read
        case_.else_ = parse_block(case_)
      end
      expect(:END)
      case_
    end

    def parse_expr(parent)
#     puts "#parse_expr"
      stack = []
      shunt_exprs.each { |token| # Token may actually be an Expr but it quacks like a token in this context
        if token.is_a? Ast::SimpleExpr
          stack.push token
        elsif oper = OPERATORS[token.kind]
          case oper[:arity]
            when 1
              e = Ast::UnExpr.new(nil, token)
              e.attach(stack.pop)
              stack.push e
            when 2
              e = Ast::BinExpr.new(nil, token)
              r = stack.pop
              l = stack.pop
              e.attachs(l, r)
              stack.push e
          else
            raise InternalError
          end
        else
          stack.push token
        end
      }
      parent.attach stack.first
    end

    # Parses list of words (cmd, env, user). Note: Called from the shunter
    def parse_simple_expr # token should be equal to #peek
#     puts "parse_simple_expr"
      case peek.kind
        when :CMD, :ENV, :USER
          expr = Ast::RuntimeExpr.new(nil, read)
          parse_idents(expr)
        when :SCHEMA
          expr = Ast::ReferenceExpr.new(nil, read)
          Ast::Reference.new(expr, expect(:IDENT))
        when :OBJECT
          expr = Ast::ReferenceExpr.new(nil, read)
          Ast::Reference.new(expr, expect(:OBJREF, :IDENT))
        when :GROUP
          expr = Ast::ReferenceExpr.new(nil, read)
          Ast::Reference.new(expr, expect(:GRPREF, :IDENT))
        when :VERSION
          expr = Ast::VersionExpr.new(nil, read)
          while VERSION_OPERATORS.include?(peek.kind)
            match = Ast::VersionMatch.new(expr, read)
            ver = Ast::Ver.new(match, expect(:VER))
          end
          !expr.matches.empty? or unexpected_token_error(peek, "version operator")
      else
        unexpected_token_error(peek, "simple expression")
      end
      expr
    end

    def parse_values(parent)
      readwhile { parse_value? parent }
    end

    # Parse a list of files. Return array of File objects. Raise an error if
    # the array is empty and :check is true
    #
    def parse_files(parent, check: true)
#     puts "#parse_files"
      check_expected "files" do
        r = []
        while !@tokenizer.eof? && (token = peek) && token.kind == :FILE
          r << Ast::File.new(parent, read)
        end
        next nil if r.empty?
        r
      end
    end

    def parse_ident?(parent) = peek&.kind == :IDENT ? Ast::Ident.new(parent, read) : nil
    def parse_ident(parent) = Ast::Ident.new(parent, expect(:IDENT))

    def parse_idents?(parent) = readwhile? { parse_ident? parent }
    def parse_idents(parent) = check_expected("identifier") { readwhile { parse_ident? parent } }


    def parse_refs(parent)
      readkinds(:IDENT, :OBJREF, :GRPREF).map { Ast::ReferenceExpr.new(parent, _1) }
    end

    # Parse a space-separated list of values. Values are IDENT, OBJREF, GRPREF, or a version match
    def parse_value?(parent)
      case peek.kind
        when :IDENT, :OBJREF, :GRPREF
          Ast::Reference.new(parent, read)
        when :VER # Default '==' operator
          ver = read
          oper = Token.new(ver.file, ver.lineno, ver.charno, "==", :EQEQ)
          value = Ast::VersionMatch.new(parent, oper)
          Ast::Ver.new(value, ver)
          value
        when *VERSION_OPERATORS
          value = Ast::VersionMatch.new(parent, read)
          Ast::Ver.new(value, expect(:VER))
          value
      else
        nil
      end
    end

    def parse_constant(parent)
      Ast::Const.new(parent, expect(CONSTANTS))
    end

    #
    # S H U N T I N G
    #
    def shunt_exprs
#     puts "#shunt_exprs"
      stack = []
      output = []
      token_args = {} # Map from list operators 'env' and 'cmd' to array of arguments

      while token = peek
        case token.kind
          when :PAREN_BEGIN; stack.push(read)
          when :PAREN_END
            read
            while op = stack.pop and op != :PAREN_BEGIN
              output << op
            end
          when :CMD, :ENV, :USER, :VERSION, :SCHEMA, :OBJECT, :GROUP
            output << parse_simple_expr
          else
            if oper = OPERATORS[token.kind]
              read
              while top = OPERATORS[stack.last&.kind]
                break if oper[:prior] > top[:prior]
                break if oper[:prior] == top[:prior] && oper[:assoc] == :right
                output << stack.pop
              end
              stack.push token
            else
              break
            end
        end
      end

      output + stack.reverse
    end

    #
    # T O K E N I Z E R  I N T E R F A C E
    #

    # Functions from tokenizer with error handling
    # TODO: Check if **opts is actually used
    def peek(**opts) = @tokenizer.peek(**opts) or error(@tokenizer.error_token)
    def read(**opts) = @tokenizer.read(**opts) or error(@tokenizer.error_token)
    def readline(**opts) = @tokenizer.readline(**opts) or error(@tokenizer.error_token)
    def readtext(indent, **opts) = @tokenizer.readtext(indent, **opts) or error(@tokenizer.error_token)
    def readkinds(*kinds, **opts) = [expect(*kinds)] + readkinds?(kinds, **opts)

    # Return nil if empty
    def readwhile(&block) = (r = readwhile?(&block)).empty? ? nil : r

    # Functions from tokenizer that accepts a nil return. FIXME this sacrifices
    # run-time performance for code clarity
    def peek?(**opts) = @tokenizer.peek(**opts)
    def read?(**opts) = @tokenizer.read(**opts)
    def readline?(**opts) = @tokenizer.readline(**opts)
    def readtext?(indent, **opts) = @tokenizer.readtext(indent, **opts)

    def readkinds?(*kinds, **opts)
      kinds = Array(kinds).flatten
      a = []
      while kinds.include? peek(**opts)&.kind
        a << read(**opts)
      end
      a
    end

    def readwhile?(&block)
      a = []
      r = yield
      while r
        a << r
        r = yield
      end
      a
    end

    # Returns token of the given kind. Generate error if not found
    def expect(*kinds)
      kinds = Array(kinds).flatten
      token = tokenizer.read
      kinds.include? token&.kind or unexpected_token_error kinds
      token
    end

    #
    # E R R O R   H A N D L I N G
    #

    # :call-seq:
    #   unexpected_token_error(token = tokenizer.error_token || tokenizer.token, *words)
    #
    # Raise an error with the message format
    #
    #   Expected KIND, ..., or KIND, got KIND
    #
    # The error will be located at the given token (default tokenizer #error or
    # #token). Note that it does not check for an error, it only displays it
    #
    def unexpected_token_error(*args)
      token = args.first.is_a?(Token) ? args.shift : tokenizer.error || tokenizer.peek_error || tokenizer.token
      token or raise ArgumentError
      words = seq Array(*args).flatten
      source = token.respond_to?(:error) && token.error || token.text
      got = (source.empty? ? "" : ", got '#{source}'")
      message = "Expected #{words}#{got}"
      error token, message
    end

    def check_expected(words, &block)
      token = peek and r = yield(token) or unexpected_token_error token, words
      r
    end

    #
    # U T I L I T I E S
    #

    # English language sequence of words. Eg 'a, b, or c'
    def seq(words)
      words.map!(&:to_s)
      case words.size
        when 1; words.first
        when 2; words.join(" or ")
        else words[0..-2].join(", ") + ", or " + words.last
      end
    end
  end
end


