
drop schema if exists prick;

create schema prick;

set search_path to prick;

create table builds (
  id integer not null generated by default as identity primary key,
  name varchar,
  version varchar,
  branch varchar,
  ref varchar,
  prick_version varchar,
  environment varchar,
  status boolean not null default false,
  created_at timestamp not null default 'now()',
  duration double generated always as (compile_duration + coalesce(execute_duration, 0)) stored,
  compile_duration double,
  execute_duration double
);

-- Built resources. Used by 'prick make'
create table resources (
  id integer not null generated by default as identity primary key,
  uid varchar not null,
  source_file varchar not null
);

create table max_ids (
  id integer not null generated by default as identity primary key,
  schema_name varchar not null,
  table_name varchar not null,
  max_id integer not null,
  file varchar not null
);

-- Meta tables
create table meta_tables (
  id integer not null generated by default as identity primary key,
  schema_name varchar not null,
  table_name varchar not null,
  source_file varchar not null
);

-- Seed tables
create table seed_tables (
  id integer not null generated by default as identity primary key,
  schema_name varchar not null,
  table_name varchar not null,
  source_file varchar not null
);

create table seed_records (
  id integer not null generated by default as identity primary key,
  seed_table_id integer not null references seed_tables(id),
  seed_record_id integer not null -- references seed_table.id
);

create table merge_table_kinds (
  id integer not null generated by default as identity primary key,
  kind varchar not null
);

insert into merge_table_kinds (kind) values ('META'), ('COPY'), ('SYNC'), ('PREPARE'), ('SEED');

create table merge_tables (
  id integer not null generated by default as identity primary key,
  schema_name varchar not null,
  table_name varchar not null,
  kind varchar not null references merge_table_kinds(kind),
  source_file varchar not null
);

