
set search_path to prick, pg_temp;

-- The status of each run
create table runs (
  id integer not null generated by default as identity primary key,
  name varchar not null, -- project name
  environment varchar not null, -- project environment
  version varchar not null, -- project version
  branch varchar not null, -- current git branch
  rev varchar not null, -- git reference (?)
  clean boolean not null, -- true if repo was up to date
  status boolean, -- true if compiled sucessfully
  prick_version varchar not null,
  created_at timestamptz not null default 'now()',
  duration double precision generated always as (compile_duration + coalesce(execute_duration, 0)) stored,
  compile_duration double precision,
  execute_duration double precision
);

-- Completed resources
--
create table resources (
  id integer not null generated by default as identity primary key,
  phase_name varchar not null,
  schema_name varchar,
  uid varchar not null unique
  -- present boolean not null default false # TODO TODO TODO
);

-- Table kinds
--
create table table_kinds (
  id integer not null generated by default as identity primary key,
  kind varchar not null unique
);

create table merge_method_kinds (
  id integer not null generated by default as identity primary key,
  kind varchar not null unique
);

insert into table_kinds (kind) values ('META'), ('SEED'), ('DATA');
insert into merge_method_kinds (kind) values ('COPY'), ('APPEND'), ('SYNC'), ('PREPARE'), ('HANDLE');

-- Tables
--
create table tables (
  id integer not null generated by default as identity primary key,
  schema_name varchar not null,
  table_name varchar not null,

  -- Table kind. META or SEED - DATA is not used atm.
  kind varchar not null references table_kinds(kind),

  -- Method to use when merging, only for informational purposes atm.
  merge_method varchar references merge_method_kinds(kind),

  -- Key field when merge method is SYNC or PREPARE. null if method is any
  -- other method
  key_field varchar,

  -- Value from current_serials aka. the next ID (starting at 1). Initially
  -- nil, assigned in after the seed phase
  serial integer,

  unique (schema_name, table_name)
);

-- Records
--
create table records (
  id integer not null generated by default as identity primary key,
  table_id integer not null references prick.tables(id),
  record_id integer not null,
  ident varchar, -- value of table.<key-field>

  unique (table_id, record_id),
  unique (table_id, ident)
);

-- Serial values (sequence next-val) for all tables in the production database.
-- It is used to ensure that new records from the source database won't
-- conflict with existing records
--
-- The serial is defined as the next value that will be read from the
-- postgres serial
create table serials (
  id integer not null generated by default as identity primary key,
--  table_id integer not null references prick.tables(id),
  schema_name varchar not null,
  table_name varchar not null,
  sequence_name varchar not null,
  value integer not null
);

/*
-- Meta tables
create table meta_tables (
  id integer not null generated by default as identity primary key,
  schema_name varchar not null,
  table_name varchar not null,
  value integer not null -- Value from current_serials aka. the next ID
);

-- Seed tables
create table seed_tables (
  id integer not null generated by default as identity primary key,
  schema_name varchar not null,
  table_name varchar not null,
  value integer not null -- Value from current_serials aka. the next ID
);

create table merge_table_kinds (
  id integer not null generated by default as identity primary key,
  kind varchar not null unique
);
*/

/*
create table merge_tables (
  id integer not null generated by default as identity primary key,
  schema_name varchar not null,
  table_name varchar not null,
  kind varchar not null references merge_table_kinds(kind)
);
*/

/*
-- Seed tables
create table seed_tables (
  id integer not null generated by default as identity primary key,
  schema_name varchar not null,
  table_name varchar not null,
  source_file varchar not null
);

create table seed_records (
  id integer not null generated by default as identity primary key,
  seed_table_id integer not null references seed_tables(id),
  seed_record_id integer not null -- references seed_table.id
);

create table merge_table_kinds (
  id integer not null generated by default as identity primary key,
  kind varchar not null
);

insert into merge_table_kinds (kind) values ('META'), ('COPY'), ('SYNC'), ('PREPARE'), ('SEED');

create table merge_tables (
  id integer not null generated by default as identity primary key,
  schema_name varchar not null,
  table_name varchar not null,
  kind varchar not null references merge_table_kinds(kind),
  source_file varchar not null
);
*/
